apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-backend
  labels:
    app: calculator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-backend
  template:
    metadata:
      labels:
        app: calculator-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: calculator-backend
          image: ghcr.io/veryoriginalik/calculator-backend:08ba9e4
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-backend
spec:
  type: ClusterIP
  selector:
    app: calculator-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
